import { useCallback, useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowLeft as ArrowLeftIcon, ArrowRight as ArrowRightIcon, Grid2X2 as GridIcon, StickyNote as NotesIcon, Play as PlayIcon, Printer as PrinterIcon, Presentation as PresentationIcon, X as CloseIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { slides, readSlideIndex } from './slides';
import { ScaledSlide } from './ScaledSlide';
import { SlideLayout } from './SlideLayout';
export default function PresentationPage() {
 const [params,setParams]=useSearchParams(); const index=readSlideIndex(params.toString(),20); const slide=slides[index];
 const print=params.has('print'), presenter=params.has('presenter');
 const [grid,setGrid]=useState(false),[notes,setNotes]=useState(false),[presenting,setPresenting]=useState(false),[elapsed,setElapsed]=useState(0);
 const touch=useRef<number|null>(null),channel=useRef<BroadcastChannel|null>(null);
 const navigate=useCallback((next:number,broadcast=true)=>{const bounded=Math.max(0,Math.min(19,next));setParams(prev=>{const p=new URLSearchParams(prev);p.set('slide',String(bounded+1));return p;},{replace:true});if(broadcast)channel.current?.postMessage({index:bounded});},[setParams]);
 useEffect(()=>{document.title=`${index+1}/20 — ${slide.title} · DSS`;},[index,slide.title]);
 useEffect(()=>{const bc=new BroadcastChannel('dss-governance-deck');channel.current=bc;bc.onmessage=e=>{if(Number.isInteger(e.data?.index))navigate(e.data.index,false);};return()=>{bc.close();channel.current=null;};},[navigate]);
 const start=useCallback(async()=>{setGrid(false);setPresenting(true);try{await document.documentElement.requestFullscreen();}catch{/* windowed fallback */}},[]);
 const stop=useCallback(()=>{setPresenting(false);if(document.fullscreenElement)void document.exitFullscreen();},[]);
 useEffect(()=>{const fn=()=>{if(!document.fullscreenElement)setPresenting(false);};document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn);},[]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('textarea,input')||print)return;if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();navigate(index+1);}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();navigate(index-1);}if(e.key==='Escape'){stop();setGrid(false);}if(e.key.toLowerCase()==='g')setGrid(v=>!v);if(e.key==='F5'){e.preventDefault();void start();}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[index,navigate,print,start,stop]);
 useEffect(()=>{if(!presenter)return;const timer=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(timer);},[presenter]);
 const swipe={onTouchStart:(e:React.TouchEvent)=>{touch.current=e.touches[0]?.clientX??null;},onTouchEnd:(e:React.TouchEvent)=>{const end=e.changedTouches[0]?.clientX;if(touch.current!==null&&end!==undefined&&Math.abs(end-touch.current)>50)navigate(index+(end<touch.current?1:-1));touch.current=null;}};
 const iconButton=(label:string,icon:React.ReactNode,action:()=>void)=><Button key={label} title={label} aria-label={label} variant="ghost" size="icon" onClick={action}>{icon}</Button>;
 if(print)return <main className="deck-print"><div className="print-toolbar"><Button onClick={()=>window.print()}><PrinterIcon/>Salvar PDF</Button></div>{slides.map(s=><div className="deck-print-page" key={s.id}><SlideLayout slide={s}/></div>)}</main>;
 const navigation=<div className="deck-navigation"><span>{slide.support?'Aprofundamento opcional':'Qualidade que se repete. Evolução que escala.'}</span><div><Button aria-label="Slide anterior" title="Slide anterior" variant="ghost" size="icon" disabled={index===0} onClick={()=>navigate(index-1)}><ArrowLeftIcon/></Button><span>{String(index+1).padStart(2,'0')} / 20</span><Button aria-label="Próximo slide" title="Próximo slide" variant="ghost" size="icon" disabled={index===19} onClick={()=>navigate(index+1)}><ArrowRightIcon/></Button></div></div>;
 if(presenting)return <main className="deck-fullscreen" {...swipe}><ScaledSlide><SlideLayout slide={slide}/></ScaledSlide><div className="present-controls">{navigation}{iconButton('Sair da apresentação',<CloseIcon/>,stop)}</div></main>;
 return <main className="deck-app"><header className="deck-toolbar"><a href="/" className="deck-wordmark">DSS <small>{presenter?'APRESENTADOR':'APRESENTAÇÃO EXECUTIVA'}</small></a><div className="deck-toolbar-actions">{presenter?<span>{Math.floor(elapsed/60)}:{String(elapsed%60).padStart(2,'0')}</span>:<>{iconButton('Visão geral',<GridIcon/>,()=>setGrid(v=>!v))}{iconButton('Notas de fala',<NotesIcon/>,()=>setNotes(v=>!v))}{iconButton('Abrir modo apresentador',<PresentationIcon/>,()=>{window.open(`${location.pathname}?presenter&slide=${index+1}`,'dss-presenter');})}{iconButton('Exportar PDF',<PrinterIcon/>,()=>{window.open(`${location.pathname}?print`,'_blank','noopener,noreferrer');})}<Button onClick={start}><PlayIcon/>Apresentar</Button></>}</div></header>
 <div className="deck-workspace">{!presenter&&<aside className="deck-sidebar"><div className="deck-sidebar-label">PRINCIPAIS · 15</div>{slides.map((s,i)=><div key={s.id}>{i===15&&<div className="deck-sidebar-label support-divider">APOIO · 5</div>}<Button variant="ghost" className={`deck-thumb ${i===index?'selected':''}`} aria-label={`Abrir slide ${s.id}: ${s.title}`} onClick={()=>{navigate(i);setGrid(false);}}><div className="thumb-preview"><ScaledSlide><SlideLayout slide={s}/></ScaledSlide></div><span className="thumb-label"><b>{s.id}</b>{s.title}</span></Button></div>)}</aside>}
 <div className="deck-main"><div className="deck-context"><span>{slide.support?'APOIO':'PRINCIPAIS'} / {slide.id}</span><span>{slide.title}</span></div>{grid?<div className="deck-overview">{slides.map((s,i)=><Button key={s.id} variant="ghost" className="overview-item" aria-label={`Selecionar slide ${s.id}`} onClick={()=>{navigate(i);setGrid(false);}}><div><ScaledSlide><SlideLayout slide={s}/></ScaledSlide></div><span>{s.id} · {s.title}</span></Button>)}</div>:<div className="deck-canvas" {...swipe}><ScaledSlide><SlideLayout slide={slide}/></ScaledSlide></div>}{navigation}{notes&&!grid&&<section className="deck-notes"><h2><NotesIcon/>Notas de fala e direção visual</h2><div>{slide.sourceNotes}</div></section>}</div>
 {presenter&&<aside className="presenter-notes"><h2>A seguir</h2><div className="next-slide">{slides[index+1]?<ScaledSlide><SlideLayout slide={slides[index+1]}/></ScaledSlide>:<p>Fim da apresentação</p>}</div><h2>Notas de fala e direção visual</h2><div className="presenter-note-text">{slide.sourceNotes}</div></aside>}
 </div></main>;
}