// @ts-nocheck
// AUTO-GENERATED by scripts/generate-portal-landing-pages.js
// Gerado em: 2026-06-01
// Componente: DssTextarea — DSS v2.2.0
//
// ⚠️ Este arquivo foi gerado automaticamente a partir do dss.meta.json.
// Para documentação completa, edite este arquivo manualmente ou
// consulte: packages/core/components/base/DssTextarea/DssTextarea.md

import React from "react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { CheckCircle, Shield, BookOpen, Package } from "lucide-react";

// ─── Dados extraídos do dss.meta.json ───────────────────────────────────────

const COMPONENT_META = {
  name: "DssTextarea",
  kebabName: "dss-textarea",
  description: "Componente DssTextarea do Design System Sansys (DSS v2.2.0). Fase 1 — Action Control interativo — campo multilinhas.",
  status: "conformant",
  seal: "DSS v2.2",
  phase: 1,
  auditDate: "2026-03-19",
  goldenReference: "DssChip",
  goldenContext: "DssInput",
}

const TOKENS_USED = [
    { token: "—", description: "Consulte o .md do componente" }
]

const DEFAULT_PROPS = [
    { prop: "variant", value: 'outlined', type: typeof "outlined" }
]

// ─── Página ─────────────────────────────────────────────────────────────────

export default function DssTextareaPage() {
  return (
    <div className="p-6 lg:p-8 max-w-6xl mx-auto space-y-8">

      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Link to="/" className="hover:text-foreground">Início</Link>
        <span>/</span>
        <Link to="/componentes/dss-button" className="hover:text-foreground">Componentes</Link>
        <span>/</span>
        <span className="text-foreground">{COMPONENT_META.name}</span>
      </div>

      {/* Header */}
      <section className="space-y-3">
        <div className="flex items-center gap-3 flex-wrap">
          <h1 className="text-3xl font-bold text-foreground">{COMPONENT_META.name}</h1>
          <Badge variant="outline" className="gap-1">
            <CheckCircle className="h-3 w-3 text-green-500" />
            {COMPONENT_META.seal}
          </Badge>
          <Badge variant="secondary">Fase {COMPONENT_META.phase}</Badge>
        </div>
        <p className="text-lg text-muted-foreground max-w-2xl">{COMPONENT_META.description}</p>
        <div className="flex gap-4 text-sm text-muted-foreground">
          <span>Auditado em: <strong>{COMPONENT_META.auditDate}</strong></span>
          <span>Status: <strong className="text-green-600">{COMPONENT_META.status}</strong></span>
        </div>
      </section>

      {/* Conformidade */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="h-5 w-5 text-blue-500" />
            Conformidade DSS
          </CardTitle>
          <CardDescription>Metadados de auditoria e governança</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="space-y-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Golden Reference</p>
              <p className="font-medium text-sm">{COMPONENT_META.goldenReference}</p>
            </div>
            <div className="space-y-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Golden Context</p>
              <p className="font-medium text-sm">{COMPONENT_META.goldenContext}</p>
            </div>
            <div className="space-y-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Fase</p>
              <p className="font-medium text-sm">{COMPONENT_META.phase}</p>
            </div>
            <div className="space-y-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Data de Auditoria</p>
              <p className="font-medium text-sm">{COMPONENT_META.auditDate}</p>
            </div>
          </div>
          
          <div className="mt-4 pt-4 border-t space-y-2">
            <p className="text-xs text-muted-foreground uppercase tracking-wide">Dimensões (defaultPreview)</p>
            <div className="flex flex-wrap gap-2">
              <span className="font-mono text-xs bg-muted px-1 py-0.5 rounded">minHeight: 88px</span>
            <span className="font-mono text-xs bg-muted px-1 py-0.5 rounded">minWidth: 240px</span>
            </div>
          </div>
          
        </CardContent>
      </Card>

      {/* Props padrão */}
      {DEFAULT_PROPS.length > 0 && DEFAULT_PROPS[0].prop !== "—" && (
        <section className="space-y-3">
          <h2 className="text-xl font-semibold flex items-center gap-2">
            <Package className="h-5 w-5" />
            Props Padrão (defaultPreview)
          </h2>
          <Card>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Prop</TableHead>
                  <TableHead>Valor Padrão</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {DEFAULT_PROPS.map((p) => (
                  <TableRow key={p.prop}>
                    <TableCell className="font-mono text-sm">{p.prop}</TableCell>
                    <TableCell className="font-mono text-xs text-muted-foreground">{String(p.value)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Card>
        </section>
      )}

      {/* Tokens */}
      {TOKENS_USED.length > 0 && (
        <section className="space-y-3">
          <h2 className="text-xl font-semibold flex items-center gap-2">
            <BookOpen className="h-5 w-5" />
            Tokens CSS Consumidos
          </h2>
          <Card>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Token</TableHead>
                  <TableHead>Descrição</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {TOKENS_USED.map((t, i) => (
                  <TableRow key={i}>
                    <TableCell className="font-mono text-xs text-blue-600 dark:text-blue-400">{t.token}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">{t.description}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Card>
        </section>
      )}

      {/* Links de documentação */}
      <Card className="border-dashed">
        <CardContent className="p-6 space-y-3">
          <CardTitle className="text-base">Documentação Completa</CardTitle>
          <CardDescription className="space-y-1">
            <p>Para a documentação completa do componente, consulte:</p>
            <ul className="mt-2 space-y-1 text-sm list-disc list-inside">
              <li>
                <code className="text-xs bg-muted px-1 rounded">
                  packages/core/components/base/DssTextarea/DssTextarea.md
                </code>
              </li>
              <li>
                <code className="text-xs bg-muted px-1 rounded">
                  packages/core/components/base/DssTextarea/DSSTEXTAREA_API.md
                </code>
              </li>
              <li>
                <code className="text-xs bg-muted px-1 rounded">
                  docs/Compliance/seals/DssTextarea/
                </code>
              </li>
            </ul>
          </CardDescription>
        </CardContent>
      </Card>

    </div>
  )
}
