<template>
<DssLayout v-bind="$attrs" container class="nf-layout" data-brand="water" :data-theme="theme">
<DssAppBar brand="water" title="Faturamento · NFAg" menu-aria-label="Abrir menu principal" />
<DssPageContainer><DssPage><DssContainer tag="main" size="lg" padding="md" gap="lg">
<header class="nf-between"><div><DssSectionTitle :level="1" size="lg" label="Check-in de configuração NFAg"/><p class="text-secondary">Prontidão cadastral e tributária para a emissão.</p></div><div class="nf-actions"><DssButton label="Relatório PDF" icon="description" variant="outline" :disabled="running || !hasResult" @click="reportOpen=true"/><DssButton label="Executar verificação" icon="play_arrow" color="primary" :loading="running" :disabled="running" @click="execute"/></div></header>
<section class="row q-col-gutter-md items-center" aria-label="Empresa emitente"><div class="col-12 col-md-5"><DssSelect v-model="companyId" :options="COMPANIES" emit-value map-options label="Empresa emitente" variant="outlined" :disabled="running"/></div><div class="col-12 col-md-7 nf-actions"><span>CNPJ {{ company.cnpj }}</span><span>{{ company.city }}</span><span>IBGE {{ company.ibge }}</span></div></section>
<DssBanner v-if="scenario==='error' && !running" variant="error">Não foi possível recuperar a última execução. Execute novamente em alguns minutos.</DssBanner>
<DssBanner v-if="scenario==='stale'" variant="warning">Resultado desatualizado. Execute novamente antes de emitir.</DssBanner>
<section class="nf-summary" aria-live="polite" :aria-busy="running"><small class="text-secondary">SITUAÇÃO DO AMBIENTE</small><h2>{{ running?'Verificação em andamento':hasResult?verdict(rows):'Aguardando primeira verificação' }}</h2><p>{{ running?`${completed} de 11 verificações concluídas`:hasResult?'Última execução demonstrativa · agora':'Selecione a empresa e inicie o check-in.' }}</p><DssLinearProgress v-if="running || scenario==='loading'" :value="completed/11" color="primary"/><div v-else class="nf-actions"><DssChip :label="`${totals.ok} aprovadas`" color="positive"/><DssChip :label="`${totals.warning} alertas`" color="warning"/><DssChip :label="`${totals.failure} falhas`" color="negative"/></div></section>
<section><div class="nf-between"><DssSectionTitle :level="2" label="Verificações de configuração"/><div class="nf-actions"><DssButton v-for="f in filters" :key="f.id" :label="f.label" :variant="filter===f.id?'unelevated':'flat'" color="primary" @click="filter=f.id"/></div></div>
<DssExpansionItem v-for="row in filtered" :key="row.id" :label="`${String(row.id).padStart(2,'0')} · ${row.title} — ${labels[row.status]}`" :caption="row.summary" :icon="icons[row.status]" class="nf-check">
<div class="nf-detail"><DssChip :label="row.blocking?'Falha bloqueante':labels[row.status]" :color="colors[row.status]"/><p>{{ row.rule }}</p><p>{{ row.impact }}</p><p class="text-secondary">Funcionalidade para correção: {{ row.destination }}</p>
